### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Tech-How** [drosoCode/Offculus#5]
Hi, this project is amazing as a way to install my Oculus software without using the online installer and then replacing the files myself. Thank you so much for making it :) When you say the OVRLibrary Service does not get installed, will I still be able to launch my "shortcuts" from the Oculus dash inside the headset? I have a shortcut to SteamVR there on the dash library because I too only use Steam with it. And how you ran OVRServiceLauncher.exe -install, is there a way to do something similar to the Library service as well? What exactly does the Library service do? Does it only affect Oculus _purchased_ content and updates?
Hope you can answer!

**Comment by Tech-How** [comment]
Also I'm getting issues where it won't let me pass and won't accept any software location I give it, saying I don't have permission. When I give it a folder that I do have write permission to, it still gives me an OVR error, presumably related to the OVR service.![image](https://user-images.githubusercontent.com/76794507/182266950-c6ca0df8-6353-4236-8834-4323ec15cf84.jpeg)

**Comment by drosoCode** [comment]
Hi,

It's been quite some time since I last launched the Oculus software, but if I remember correctly nothing is available except the headset settings.
So, I'm not sure that you could use the shortcuts from the oculus dash (if you only want to start SteamVR, you can do so direcly on your PC and steam will take care of launching the oculus software).

There is probably a way to install the OVRLibraryService as well, but as I didn't bought any game from the Oculus Store, I haven't looked into how to do so.
The OVRLibraryService seems to be used to manage your game library, so any purchased content on the Oculus store will probably be unavailable if this service is not installed (but the games bought on steam will still work).

As for your error, I wouldn't be surprised if some things have changed in the installation process of the Oculus software, these scripts are already 2 years old and haven't been updated since, so there is probably some actions that are missing compared to the newest versions of the installer.

Unfortunately, I don't have any time to work on this project, but if you want to try to update it, I will gladly accept a PR, you can also learn more about how I made these scripts on [this post](https://thomasz.me/2020/10/04/use-your-oculus-rift-completly-offline/).
